/* Generated By:JavaCC: Do not edit this line. SQLParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int KW_AND = 8;
  /** RegularExpression Id. */
  int KW_OR = 9;
  /** RegularExpression Id. */
  int KW_CREATE = 10;
  /** RegularExpression Id. */
  int KW_CHECK = 11;
  /** RegularExpression Id. */
  int KW_PRIMARY = 12;
  /** RegularExpression Id. */
  int KW_FOREIGN = 13;
  /** RegularExpression Id. */
  int KW_KEY = 14;
  /** RegularExpression Id. */
  int KW_REFERENCES = 15;
  /** RegularExpression Id. */
  int KW_DROP = 16;
  /** RegularExpression Id. */
  int KW_TABLE = 17;
  /** RegularExpression Id. */
  int KW_SELECT = 18;
  /** RegularExpression Id. */
  int KW_FROM = 19;
  /** RegularExpression Id. */
  int KW_WHERE = 20;
  /** RegularExpression Id. */
  int KW_INSERT = 21;
  /** RegularExpression Id. */
  int KW_INTO = 22;
  /** RegularExpression Id. */
  int KW_VALUES = 23;
  /** RegularExpression Id. */
  int KW_DELETE = 24;
  /** RegularExpression Id. */
  int KW_UPDATE = 25;
  /** RegularExpression Id. */
  int KW_SET = 26;
  /** RegularExpression Id. */
  int KW_HELP = 27;
  /** RegularExpression Id. */
  int KW_TABLES = 28;
  /** RegularExpression Id. */
  int KW_DESCRIBE = 29;
  /** RegularExpression Id. */
  int KW_QUIT = 30;
  /** RegularExpression Id. */
  int KW_INT = 31;
  /** RegularExpression Id. */
  int KW_CHAR = 32;
  /** RegularExpression Id. */
  int KW_DECIMAL = 33;
  /** RegularExpression Id. */
  int SYM_PLUS = 34;
  /** RegularExpression Id. */
  int SYM_MINUS = 35;
  /** RegularExpression Id. */
  int SYM_STAR = 36;
  /** RegularExpression Id. */
  int SYM_SLASH = 37;
  /** RegularExpression Id. */
  int SYM_EQUAL = 38;
  /** RegularExpression Id. */
  int SYM_EXCLEQUAL = 39;
  /** RegularExpression Id. */
  int SYM_LESS = 40;
  /** RegularExpression Id. */
  int SYM_MORE = 41;
  /** RegularExpression Id. */
  int SYM_LESSEQUAL = 42;
  /** RegularExpression Id. */
  int SYM_MOREEQUAL = 43;
  /** RegularExpression Id. */
  int IDENTIFIER = 44;
  /** RegularExpression Id. */
  int INT_LITERAL = 45;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 46;
  /** RegularExpression Id. */
  int STRING_LITERAL = 47;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"\\r\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"AND\"",
    "\"OR\"",
    "\"CREATE\"",
    "\"CHECK\"",
    "\"PRIMARY\"",
    "\"FOREIGN\"",
    "\"KEY\"",
    "\"REFERENCES\"",
    "\"DROP\"",
    "\"TABLE\"",
    "\"SELECT\"",
    "\"FROM\"",
    "\"WHERE\"",
    "\"INSERT\"",
    "\"INTO\"",
    "\"VALUES\"",
    "\"DELETE\"",
    "\"UPDATE\"",
    "\"SET\"",
    "\"HELP\"",
    "\"TABLES\"",
    "\"DESCRIBE\"",
    "\"QUIT\"",
    "\"int\"",
    "\"char\"",
    "\"decimal\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "<IDENTIFIER>",
    "<INT_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<STRING_LITERAL>",
    "\";\"",
    "\"(\"",
    "\",\"",
    "\")\"",
  };

}
